services:
  - type: web
    name: groq-rag-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0
    plan: free
